#!/usr/bin/env python3
with open('/workspace/ziwei-beasts/src/App.tsx', 'r') as f:
    content = f.read()

old = ('function RevealAnimation({ beast, onDone }: { beast: typeof BEASTS[number]; onDone: () => void }) {\n'
       '  const [phase, setPhase] = useState(0)\n'
       '  useEffect(() => {\n'
       '    const ts = [\n'
       '      setTimeout(() => setPhase(1), 500),\n'
       '      setTimeout(() => setPhase(2), 1600),\n'
       '      setTimeout(() => setPhase(3), 2800),\n'
       '      setTimeout(() => onDone(), 5200),\n'
       '    ]\n'
       '    return () => ts.forEach(clearTimeout)\n'
       '  }, [])\n'
       '  return (\n'
       '    <div className="reveal-overlay">\n'
       '      <Stars />\n'
       '      <button className="reveal-close" onClick={onDone} aria-label="Skip">\n'
       '        <svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M3 3 L15 15 M15 3 L3 15" stroke="rgba(237,232,245,0.5)" strokeWidth="1.5" strokeLinecap="round"/></svg>\n'
       '      </button>\n'
       '      <div className={`reveal-iris ${phase >= 1 ? \'open\' : \'\'}`} />\n'
       '      <div className={`reveal-center ${phase >= 2 ? \'vis\' : \'\'}`}>\n'
       '        <div className="reveal-glow" style={{ background: `radial-gradient(circle, ${beast.glowColor} 0%, transparent 65%)` }}/>\n'
       '        <img src={beast.icon} alt={beast.name} className="reveal-img" />\n'
       '        <div className="reveal-particles">\n'
       '          {Array.from({ length: 20 }, (_, i) => {\n'
       '            const angle = (i / 20) * 360\n'
       '            const dist = 50 + (i % 4) * 20\n'
       '            const delay = (i % 6) * 0.12\n'
       '            return (\n'
       '              <div key={i} className="r-particle"\n'
       '                style={{ transform: `rotate(${angle}deg) translateX(${dist}px)`, animationDelay: `${delay}s` }}\n'
       '              />\n'
       '            )\n'
       '          })}\n'
       '        </div>\n'
       '      </div>\n'
       '      {phase >= 3 && (\n'
       '        <div className="reveal-name-block">\n'
       '          <div className="reveal-branch" style={{ color: beast.color, borderColor: `${beast.color}50` }}>\n'
       '            {beast.zodiac} · {beast.branch} Branch · {beast.palace}\n'
       '          </div>\n'
       '          <div className="reveal-name-lg">{beast.name}</div>\n'
       '          <div className="reveal-tag-sm" style={{ color: beast.color }}>{beast.tagline}</div>\n'
       '        </div>\n'
       '      )}\n'
       '    </div>\n'
       '  )\n'
       '}\n')

new = ('// Full reveal ceremony: beast emerges → speaks → shows powers\n'
       'function RevealAnimation({ beast, onDone }: { beast: typeof BEASTS[number]; onDone: () => void }) {\n'
       '  const [phase, setPhase] = useState(0)\n'
       '  const quotes = [\n'
       '    { label: "I am here.", text: beast.desc },\n'
       '    { label: "The Encounter", text: beast.narrative.opening.slice(0, 110) + "..." },\n'
       '    { label: "Your Nature", text: beast.narrative.coreNature.slice(0, 110) + "..." },\n'
       '    { label: "The Invitation", text: beast.narrative.guidance.slice(0, 100) + "..." },\n'
       '  ]\n'
       '  useEffect(() => {\n'
       '    const ts = [\n'
       '      setTimeout(() => setPhase(1), 600),\n'
       '      setTimeout(() => setPhase(2), 2200),\n'
       '      setTimeout(() => setPhase(3), 4200),\n'
       '      setTimeout(() => setPhase(4), 6000),\n'
       '      setTimeout(() => onDone(), 7600),\n'
       '    ]\n'
       '    return () => ts.forEach(clearTimeout)\n'
       '  }, [])\n'
       '  const q = quotes[phase - 1] ?? quotes[0]\n'
       '  return (\n'
       '    <div className="reveal-overlay">\n'
       '      <Stars />\n'
       '      <button className="reveal-close" onClick={onDone} aria-label="Skip">\n'
       '        <svg width="18" height="18" viewBox="0 0 18 18" fill="none"><path d="M3 3 L15 15 M15 3 L3 15" stroke="rgba(237,232,245,0.5)" strokeWidth="1.5" strokeLinecap="round"/></svg>\n'
       '      </button>\n'
       '      <div className={`reveal-iris ${phase >= 1 ? "open" : ""}`} />\n'
       '      <div className={`reveal-center ${phase >= 2 ? "vis" : ""}`}>\n'
       '        <div className="reveal-glow" style={{ background: `radial-gradient(circle, ${beast.glowColor} 0%, transparent 65%)` }}/>\n'
       '        <img src={beast.icon} alt={beast.name} className="reveal-img" />\n'
       '        <div className="reveal-particles">\n'
       '          {Array.from({ length: 20 }, (_, i) => (\n'
       '            <div key={i} className="r-particle"\n'
       '              style={{ transform: `rotate(${(i / 20) * 360}deg) translateX(${50 + (i % 4) * 20}px)`, animationDelay: `${(i % 6) * 0.15}s` }}\n'
       '            />\n'
       '          ))}\n'
       '        </div>\n'
       '      </div>\n'
       '      <div className={`reveal-name-block ${phase >= 2 ? "vis" : ""}`}>\n'
       '        <div className="reveal-branch" style={{ color: beast.color, borderColor: `${beast.color}50` }}>\n'
       '          {beast.cnName} · {beast.element}\n'
       '        </div>\n'
       '        <div className="reveal-name-lg">{beast.name}</div>\n'
       '        <div className="reveal-tag-sm" style={{ color: beast.color }}>{beast.tagline}</div>\n'
       '      </div>\n'
       '      <div className={`reveal-quote-card ${phase >= 3 ? "vis" : ""}`} style={{ borderColor: `${beast.color}30` }}>\n'
       '        <div className="rq-label" style={{ color: beast.color }}>{q.label}</div>\n'
       '        <p className="rq-text">"{q.text}"</p>\n'
       '      </div>\n'
       '      <div className={`reveal-skills-strip ${phase >= 4 ? "vis" : ""}`}>\n'
       '        <div className="reveal-skills-label">Your Guardian Powers</div>\n'
       '        <div className="reveal-skills-pills">\n'
       '          {(beast.skills as unknown as string[]).map((sid) => {\n'
       '            const name = (sid as string).split("-").map((w: string) => w[0].toUpperCase() + w.slice(1)).join(" ")\n'
       '            return (\n'
       '              <span key={sid as string} className="reveal-skill-pill"\n'
       '                style={{ color: beast.color, borderColor: `${beast.color}40` }}>\n'
       '                {name}\n'
       '              </span>\n'
       '            )\n'
       '          })}\n'
       '        </div>\n'
       '      </div>\n'
       '      <div className="reveal-dots">\n'
       '        {[1,2,3,4].map(n => (\n'
       '          <div key={n} className={`reveal-dot ${phase >= n ? "active" : ""}`}\n'
       '            style={{ background: phase >= n ? beast.color : "rgba(255,255,255,0.15)" }} />\n'
       '        ))}\n'
       '      </div>\n'
       '    </div>\n'
       '  )\n'
       '}\n')

if old in content:
    new_content = content.replace(old, new, 1)
    with open('/workspace/ziwei-beasts/src/App.tsx', 'w') as f:
        f.write(new_content)
    print('SUCCESS: replaced')
    print('Old:', len(old), 'New:', len(new))
else:
    print('NOT FOUND - searching for close match...')
    idx = content.find('function RevealAnimation')
    print('RevealAnimation at char:', idx)
    print('Next 200 chars:', repr(content[idx:idx+200]))